import 'package:mobx/mobx.dart';
import '../../../data/models/inquiry_model.dart';
import '../../../data/repositories/inquiry_repository.dart';
import '../../../shared/utils/email_service.dart';

part 'inquiry_store.g.dart';

class InquiryStore = _InquiryStore with _$InquiryStore;

abstract class _InquiryStore with Store {
  final InquiryRepository inquiryRepository;
  final EmailService emailService;

  _InquiryStore(this.inquiryRepository, this.emailService);

  @observable
  bool isLoading = false;

  @observable
  String? error;

  @observable
  bool isSuccess = false;

  @action
  Future<void> submitInquiry({
    required String clientName,
    required String email,
    required String? phoneNumber,
    required String projectType,
    required String? message,
    required String? budgetRange,
    required String? timeline,
  }) async {
    try {
      isLoading = true;
      error = null;
      isSuccess = false;

      final inquiry = Inquiry(
        id: '', // Will be generated by Supabase
        clientName: clientName,
        email: email,
        phoneNumber: phoneNumber,
        projectType: projectType,
        message: message,
        budgetRange: budgetRange,
        timeline: timeline,
        createdAt: DateTime.now(),
      );

      await inquiryRepository.createInquiry(inquiry);

      await emailService.sendInquiryEmail(
        clientName: clientName,
        clientEmail: email,
        projectType: projectType,
        message: message ?? '',
        phoneNumber: phoneNumber,
        budgetRange: budgetRange,
        timeline: timeline,
      );

      isSuccess = true;
      isLoading = false;
    } catch (e) {
      error = e.toString();
      isLoading = false;
    }
  }

  @action
  void clearError() {
    error = null;
  }

  @action
  void resetForm() {
    isSuccess = false;
    error = null;
  }
}
